apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "pp.labels" . | nindent 4 }}
spec:
  schedule: "10 1 * * *" # Set task start time in UTC time zone ( Every Day )
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 5
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "pp.serviceAccountName" . }}
          imagePullSecrets:
            - name: {{ .Values.image.pullSecret }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            ports:
              - name: http
                containerPort: 80
                protocol: TCP
            startupProbe:
              httpGet:
                path: /health
                port: http
              timeoutSeconds: 7
              failureThreshold: 12
            envFrom:
              - configMapRef:
                  name: {{ .Chart.Name }}-env
